# Generated by Django 2.1.2 on 2018-10-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('fecha_nac', models.DateField(null=True, verbose_name='Fecha')),
                ('dni', models.IntegerField(null=True)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Comprador',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('Fruta', 'FRUTA'), ('Verdura', 'VERDURA')], max_length=15)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('fecha_nac', models.DateField(null=True, verbose_name='Fecha')),
                ('dni', models.IntegerField(null=True)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('zona_com', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Vendedor',
            },
        ),
    ]
